### ISSUE TITLE
CAnnot run wit default settings

### ISSUE THREAD

**Issue by mkaraoz** [YalcinYolalan/WSSAT#13]
When I select a wsdl file and hit Scan SOAP Service I get Please Select WSDL List File!!! error.

Steps to reproduce:
1. Open \WSSAT-master\WSSAT\bin\Debug\WSSAT.exe 
2. hit select wsdl list file and select a wsdl file on local disk
3. click on Scan SOAP Service(s) button

Error window pops up.

**Comment by YalcinYolalan** [comment]
You must select "WSDL List File" which is just txt file containing your wsdl addresses. Please check Usage Wiki https://github.com/YalcinYolalan/WSSAT/wiki/Usage for further information.

![image](https://user-images.githubusercontent.com/17210239/52613976-26f95e80-2ea1-11e9-82bc-e33a5172c466.png)
