### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by 1N3** [YalcinYolalan/WSSAT#8]
Hi, this might be a dumb question but how do you install this from Linux? I didn't see any documentation anywhere.

**Comment by YalcinYolalan** [comment]
Hi, WSSAT is a Windows executable, try to use virtual machine.

**Comment by benmcewan1** [comment]
Yes but theres no installation instructions.  Says something to that effect in README.md 

Please make it clear how to install this.  Looks like incredible tool, want to use it.

Thanks

**Comment by YalcinYolalan** [comment]
Please read: 
https://github.com/YalcinYolalan/WSSAT/wiki/Installation

Thanks
